// components/Pokemon/Search.vue
<script setup>
const searchInput = ref('')
const clearSearch = () => {
  searchInput.value = ''
}
</script>

<template>
  <div class="border border-blue-400 flex items-center justify-between p-1 rounded-full mb-10">
    <div class="flex-grow flex items-center">
      <Icon name="heroicons:magnifying-glass" class="text-lg ml-2 cursor-pointer"/>
      <input type="text" class="flex-grow outline-none text-lg p-2 ml-2" v-model="searchInput" placeholder="Pokemon name, number or type">
    </div>
    <div class="flex gap-5 items-center">
      <Icon name="heroicons:x-mark" class="text-xl cursor-pointer" @click="clearSearch"/>
      <button class="bg-yellow-400 text-blue-400 py-2 px-4 rounded-full" @click="$emit('search', searchInput)">Search</button>
    </div>
  </div>
</template>

// components/Search.tsx
import Image from "next/image";

const Search = () => {
    return (
        <section className={"w-full bg-white rounded-2xl mt-10 mb-10"}>
            <form className={"flex items-center justify-between py-2 pr-2 pl-4"}>
                <div className={"flex items-center gap-4"}>
                    <Image src={"/icons/search.svg"} alt={"Search Icon"} width={24} height={24}
                           className={"text-darkBlue fill-current"}/>
                    <input type="text" placeholder={"Pokemon name, number or type"}
                           className={"outline-none text-darkBlue placeholder-darkBlue placeholder:font-medium w-[230px]"}/>
                </div>
                <button className={"text-darkBlue bg-yellow py-3 px-12 rounded-lg font-bold"}>
                    Search
                </button>
            </form>
        </section>
    );
};

export default Search;
